os: linux
language: python
dist: xenial
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

stages:
  - test
  - name: deploy
    if: tag IS present

before_install:
  - pip install --upgrade pip
  - pip install poetry
install:
  - poetry install --no-root -v
script:
  - make ci
  - make cover
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: deploy
      os: linux
      language: python
      dist: xenial
      python: "3.8"
      script: skip
      # before_deploy:
      #   - poetry config http-basic.pypi __token__ $PYPI_PASSWORD
      deploy:
        provider: script
        script: poetry publish --build
        on:
          tags: true
